version: 2
jobs:
  build:
    working_directory: ~/splash
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: yarn
      - run: yarn run test
      - persist_to_workspace:
          root: ~/splash
          paths:
            - node_modules
      - store_test_results:
          path: ~/splash/junit.xml

  staging:
    # TODO: testflight release
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/splash/ios
    environment:
      FL_OUTPUT_DIR: /Users/distiller/splash/output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout:
          path: /Users/distiller/splash
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      # Not using a workspace here as Node and Yarn versions
      # differ between the macOS image and the Docker containers above.
      - run: yarn
      - run: bundle install
      - run: bundle exec fastlane test
      - run:
          command: cp $FL_OUTPUT_DIR/scan/report.junit $FL_OUTPUT_DIR/scan/results.xml
          when: always
      - store_artifacts:
          path: /Users/distiller/splash/output
      - store_test_results:
          path: /Users/distiller/splash/output/scan

  master:
    # TODO: codepush release
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/splash/ios
    environment:
      FL_OUTPUT_DIR: /Users/distiller/splash/output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout:
          path: /Users/distiller/splash
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      # Not using a workspace here as Node and Yarn versions
      # differ between the macOS image and the Docker containers above.
      - run: yarn
      - run: bundle install
      - run: bundle exec fastlane test
      - run:
          command: cp $FL_OUTPUT_DIR/scan/report.junit $FL_OUTPUT_DIR/scan/results.xml
          when: always
      - store_artifacts:
          path: /Users/distiller/splash/output
      - store_test_results:
          path: /Users/distiller/splash/output/scan

  release:
    # TODO: full app store release
    macos:
      xcode: "9.0"
    working_directory: /Users/distiller/splash/ios
    environment:
      FL_OUTPUT_DIR: /Users/distiller/splash/output
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout:
          path: /Users/distiller/splash
      - run:
          name: Set Ruby Version
          command:  echo "ruby-2.4" > ~/.ruby-version
      # Not using a workspace here as Node and Yarn versions
      # differ between the macOS image and the Docker containers above.
      - run: yarn
      - run: bundle install
      - run: bundle exec fastlane test
      - run:
          command: cp $FL_OUTPUT_DIR/scan/report.junit $FL_OUTPUT_DIR/scan/results.xml
          when: always
      - store_artifacts:
          path: /Users/distiller/splash/output
      - store_test_results:
          path: /Users/distiller/splash/output/scan


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - staging:
        requires:
          - build
          filters:
            only: staging
      - master:
        requires:
          - build
          filters:
            only: master
      - release:
        requires:
          - build
          filters:
            only: release


