# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hexa' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hexa

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'hexaTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hexa-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hexa-tvOS

  target 'hexa-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
